basket:
  translatable_attributes: [:name]
  views: ['edit']
topic_type:
  translatable_attributes: [:name, :description]
  views: ['edit']
search_source:
  translatable_attributes: [:title, :source_credit]
  views: ['show', 'edit']
license:
  translatable_attributes: [:name, :description]
  views: ['show', 'edit']
extended_field:
  translatable_attributes: [:label, :example]
  views: ['show', 'edit']
  redefine_find: false
