basket:
  translatable_attributes: [:name, :index_page_extra_side_bar_html]
  views: ['edit']
topic_type:
  translatable_attributes: [:name, :description]
  views: ['edit']
search_source:
  translatable_attributes: [:title, :source_credit]
  views: ['show', 'edit']
license:
  translatable_attributes: [:name, :description]
  views: ['show', 'edit']
extended_field:
  translatable_attributes: [:label, :example]
  views: ['show', 'edit']
  redefine_find: false
system_setting:
  translatable_attributes: [:value]
  controller: configure
  views: ['section']
  additional_columns:
    takes_translations:
      type: boolean
      default: false
configurable_setting:
  translatable_attributes: [:value]
  controller: baskets
  views: ['appearance']
feed:
  translatable_attributes: [:title]
  controller: baskets
  views: ['homepage_options']

